name: buildchecks
# Build only on master branch changes in some directory
# to avoid unecessary energy using for GitHub machines
on:
  push:
    branches: [ testing ]
    paths:
      - 'app/**'
      - 'gradle/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'app/**'
      - 'gradle/**'
      - '.github/workflows/'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 8
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '8'
    - name: Build
      run: ./gradlew assembleDebug --stacktrace --info
    - name: Save artifact
      uses: actions/upload-artifact@v4
      with:
        name: Video-Transcoder.apk
        path: app/build/outputs/apk/debug/app-debug.apk
    - name: Check lint
      run: ./gradlew lintRelease
    - name: Run unit tests
      run: ./gradlew testReleaseUnitTest
    - name: Upload unit test reports
      uses: actions/upload-artifact@v4
      with:
        name: unittestsReport.htm
        path: app/build/reports/tests/testReleaseUnitTest/index.html
    - name: FindBugs
      run: ./gradlew findbugs
